
* An implementation of GTD using Org-mode

** Background
I have ADHD, and I have a lot of trouble keeping track of and prioritizing my tasks. I've tried a lot of different organizational systems over the years, to varying degrees of success. Most recently, I read the *second edition* of _Getting Things Done_ by David Allen and was very impressed with what was on offer. (I had read the first edition some years prior and been unimpressed; the earlier edition is aimed squarely at CEO types and is somewhat confusingly written. The second edition remedies these problems.) So, I decided to try to implement GTD in my own life and see if it made a difference.

But, increasingly, I live out of Emacs, and specifically Org-roam, so I needed an implementation of GTD in Org if I was going to have any hope of keeping up with it. (Minimize inboxes, Allen says, and I agree; if most of my life is in Org, that's where my system should live, too.)

I first tried Org-gtd, an existing package that aims to do exactly that. It has a lot of neat features that I haven't even got close to mimicking yet. But, it had a few crucial flaws. Most seriously, it doesn't actually follow the [[https://github.com/Trevoke/org-gtd.el][Org-gtd]] workflow, in that it doesn't contain a distinction between things that should be filed as "Someday" and things that should be filed in the "Tickler" (terms to be discussed later, if you're not familiar); all tasks that are not put into "Projects" or "Next Actions" have to be scheduled. Moreover, the owner of the package has been aware of this problem for some time and does not seem particularly interested in fixing it; I think they are happy with how it works for them. And fair enough. But I wanted something closer to GTD proper.

I looked next at a bunch of blogs that talked about implementing GTD in Org, and those had a heavy influence on what I ended up with, but none of them quite fit what I wanted. There were two that I especially spent a lot of time with:  [[https://github.com/rougier/emacs-gtd][GitHub - rougier/emacs-gtd: Get Things Done with Emacs]] had a lot of useful info, but again didn't quite follow GTD as strictly as I wanted (their agenda shows them open TODOs, and they keep recurring meetings, events, etc. in separate files rather than having one Tickler. [[https://desmondrivet.com/2023/12/05/gtd-org-mode][Implementing GTD in Emacs With Org Mode - Desmond Rivet]] gave me some things I needed about agenda sorting strategies but kept all projects, next actions, ticklers, etc. in one file, and required a lot of manual assigning of properties, etc. I didn't want to make a system that was going to require so much manual input that I would abandon it. (I have literally hundreds of tasks going at any particular time.)

** The system I wanted to implement

GTD, if you're not familiar with it, can be summarized very quickly.
